"""added reverse payment status

Revision ID: 1d005932e9b0
Revises: e0788e906025
Create Date: 2026-09-23 14:26:47.508815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d005932e9b0'
down_revision = 'e0788e906025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('pending', 'successful', 'failed', 'cancelled', 'refunded'),
               type_=sa.Enum('pending', 'successful', 'failed', 'cancelled', 'refunded', 'reversed'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'successful', 'failed', 'cancelled', 'refunded', 'reversed'),
               type_=mysql.ENUM('pending', 'successful', 'failed', 'cancelled', 'refunded'),
               existing_nullable=False)

    # ### end Alembic commands ###
