"""add pesapal order tracking id to payment

Revision ID: 1d1172bc4cfe
Revises: b7882e36be6c
Create Date: 2026-09-19 12:50:51.537283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1172bc4cfe'
down_revision = 'b7882e36be6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pesapal_order_tracking_id', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint(None, ['pesapal_order_tracking_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pesapal_order_tracking_id')

    # ### end Alembic commands ###
