"""add service images and links

Revision ID: 44d5be7e8efb
Revises: 39686e3912ed
Create Date: 2026-10-07 18:01:26.178321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44d5be7e8efb'
down_revision = '39686e3912ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('link_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('link_label', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('link_label')
        batch_op.drop_column('link_url')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
