"""create payment settings

Revision ID: 4f8256e25cb8
Revises: 5de95e0bfc5d
Create Date: 2026-09-26 14:34:12.554679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8256e25cb8'
down_revision = '5de95e0bfc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_settings',
    sa.Column('setting_key', sa.String(length=50), nullable=False),
    sa.Column('mpesa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mpesa_paybill', sa.String(length=50), nullable=True),
    sa.Column('mpesa_till', sa.String(length=50), nullable=True),
    sa.Column('mpesa_business_name', sa.String(length=200), nullable=True),
    sa.Column('airtel_enabled', sa.Boolean(), nullable=False),
    sa.Column('airtel_money_number', sa.String(length=50), nullable=True),
    sa.Column('airtel_business_name', sa.String(length=200), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('setting_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_settings')
    # ### end Alembic commands ###
