"""add tour images

Revision ID: 5de95e0bfc5d
Revises: 61c7cb51a7d5
Create Date: 2026-09-25 21:56:01.719638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de95e0bfc5d'
down_revision = '61c7cb51a7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('gallery_images', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('gallery_images')
        batch_op.drop_column('cover_image')

    # ### end Alembic commands ###
