"""add tour duration

Revision ID: 61c7cb51a7d5
Revises: cfe762592318
Create Date: 2026-09-25 19:25:39.160985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61c7cb51a7d5'
down_revision = 'cfe762592318'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_nights', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('duration_nights')
        batch_op.drop_column('duration_days')

    # ### end Alembic commands ###
