"""add guest inquiries

Revision ID: 882f1ede31de
Revises: 9b7c2f4d1a6e
Create Date: 2026-10-09 11:42:29.334093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882f1ede31de'
down_revision = '9b7c2f4d1a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_inquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'resolved', name='guest_inquiry_status'), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guest_inquiries')
    # ### end Alembic commands ###
