"""tours table created

Revision ID: 98594574b339
Revises: 7aa9f609c8e3
Create Date: 2026-08-14 17:14:33.570141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98594574b339'
down_revision = '7aa9f609c8e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tours',
    sa.Column('tour_name', sa.String(length=100), nullable=False),
    sa.Column('tour_operator_id', sa.Integer(), nullable=False),
    sa.Column('charges', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('destination', sa.String(length=200), nullable=False),
    sa.Column('departure_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tour_operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tours')
    # ### end Alembic commands ###
