"""payment method changed

Revision ID: 9f0433a330fa
Revises: 4e2d58142399
Create Date: 2026-09-01 15:49:11.076719

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f0433a330fa'
down_revision = '4e2d58142399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('Mpesa', 'Visa', 'Bank_transfer'),
               type_=sa.Enum('mpesa', 'visa', 'bank_transfer'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.Enum('mpesa', 'visa', 'bank_transfer'),
               type_=mysql.ENUM('Mpesa', 'Visa', 'Bank_transfer'),
               existing_nullable=False)

    # ### end Alembic commands ###
