"""add pesapal confirmation code

Revision ID: aaf2c68d2c32
Revises: e865118cbb05
Create Date: 2026-09-23 14:53:13.015222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaf2c68d2c32'
down_revision = 'e865118cbb05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pesapal_confirmation_code', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint(None, ['pesapal_confirmation_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pesapal_confirmation_code')

    # ### end Alembic commands ###
