"""add refund reference

Revision ID: b7882e36be6c
Revises: b77195f41d1b
Create Date: 2026-09-09 17:19:54.673289

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = 'b7882e36be6c'
down_revision = 'b77195f41d1b'
branch_labels = None
depends_on = None


def upgrade():

    connection = op.get_bind()

    refunds = connection.execute(
        sa.text("SELECT id FROM refunds")
    )

    for refund in refunds:

        reference = str(uuid.uuid4())

        refund_id = refund[0]

        connection.execute(
            sa.text("""
                UPDATE refunds
                SET refund_reference = :reference
                WHERE id = :refund_id
            """),
            {
                "reference": reference,
                "refund_id": refund_id
            }
        )

    with op.batch_alter_table("refunds", schema=None) as batch_op:
        batch_op.alter_column(
            "refund_reference",
            existing_type=sa.String(length=250),
            nullable=False
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refunds', schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_refunds_refund_reference",
            type="unique"
        )
        batch_op.drop_column('refund_reference')

    # ### end Alembic commands ###
