"""create tour accommodation

Revision ID: bb75ac0c414f
Revises: c5f4d63f5089
Create Date: 2026-09-25 18:02:29.859701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb75ac0c414f'
down_revision = 'c5f4d63f5089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tour_accommodations',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.Enum('budget', 'mid_range', 'luxury'), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=False),
    sa.Column('room_type', sa.String(length=200), nullable=False),
    sa.Column('meal_plan', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_accommodations')
    # ### end Alembic commands ###
