"""revenue target table created.

Revision ID: d626c9d8dcf7
Revises: 9f0433a330fa
Create Date: 2026-09-08 16:02:30.610523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd626c9d8dcf7'
down_revision = '9f0433a330fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revenue_targets',
    sa.Column('target_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name='check_valid_target_period'),
    sa.CheckConstraint('target_amount > 0', name='check_positive_target_amount'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revenue_targets')
    # ### end Alembic commands ###
