"""Add departure and update bookingrelationship

Revision ID: d9a9cd702698
Revises: 47584e20dfae
Create Date: 2026-08-24 20:25:29.196151

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9a9cd702698'
down_revision = '47584e20dfae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departures',
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('price_per_person', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('capacity > 0', name='check_positive_departure_capacity'),
    sa.CheckConstraint('end_date >= start_date', name='check_valid_departure_dates'),
    sa.ForeignKeyConstraint(['tour_id'], ['tours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('bookings_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'departures', ['departure_id'], ['id'])
        batch_op.drop_column('tour_id')

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.drop_column('capacity')
        batch_op.drop_column('departure_date')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    with op.batch_alter_table('tours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('departure_date', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('capacity', mysql.INTEGER(), autoincrement=False, nullable=False))

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tour_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('bookings_ibfk_1'), 'tours', ['tour_id'], ['id'])
        batch_op.drop_column('departure_id')

    op.drop_table('departures')
    # ### end Alembic commands ###
