"""payment method table updated

Revision ID: e0788e906025
Revises: 1d1172bc4cfe
Create Date: 2026-09-23 13:13:58.242399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0788e906025'
down_revision = '1d1172bc4cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('mpesa', 'visa', 'bank_transfer'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('mpesa', 'visa', 'bank_transfer'),
               nullable=False)

    # ### end Alembic commands ###
