"""expand payment methods

Revision ID: e865118cbb05
Revises: 1d005932e9b0
Create Date: 2026-09-23 14:34:14.503427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e865118cbb05'
down_revision = '1d005932e9b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('mpesa', 'visa', 'bank_transfer'),
               type_=sa.Enum('mpesa', 'visa', 'mastercard', 'amex', 'bank_transfer'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.Enum('mpesa', 'visa', 'mastercard', 'amex', 'bank_transfer'),
               type_=mysql.ENUM('mpesa', 'visa', 'bank_transfer'),
               existing_nullable=True)

    # ### end Alembic commands ###
