"""add airtel money and payment verification

Revision ID: fc62b2d1de72
Revises: 4f8256e25cb8
Create Date: 2026-09-26 15:02:42.327278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc62b2d1de72'
down_revision = '4f8256e25cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('payment_method',
               existing_type=mysql.ENUM('mpesa', 'visa', 'mastercard', 'amex', 'bank_transfer'),
               type_=sa.Enum('mpesa', 'airtel_money', 'visa', 'mastercard', 'amex', 'bank_transfer'),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'users', ['verified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('payment_method',
               existing_type=sa.Enum('mpesa', 'airtel_money', 'visa', 'mastercard', 'amex', 'bank_transfer'),
               type_=mysql.ENUM('mpesa', 'visa', 'mastercard', 'amex', 'bank_transfer'),
               existing_nullable=True)
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verified_by')

    # ### end Alembic commands ###
